# Fixtures needed for puppetlabs_spec_helper
fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '3.2.1'
  symlinks:
    irc: "#{source_dir}"

